In [1]:
l=[1,2,3,4]
k=[5,6,7,8]
l+k

[1, 2, 3, 4, 5, 6, 7, 8]

In [2]:
import numpy as np
l=[1,2,3,4]
k=[5,6,7,8]
ar1 = np.array(l)
ar2 = np.array(k)
print(ar1)
print(ar2)

[1 2 3 4]
[5 6 7 8]


In [3]:
import numpy as np
l=[1,2,3,4,2.3]
k=[5,6,7,8,4.5]
ar1 = np.array(l)
ar2 = np.array(k)
print(ar1)
print(ar2)

[1.  2.  3.  4.  2.3]
[5.  6.  7.  8.  4.5]


In [4]:
import numpy as np
l=[1,2,3,4,2.3]
k=[5,6,7,8,4.5]
ar1 = np.array(l)
ar2 = np.array(k)
print(ar1)
print(ar2)
print(ar1+ar2)

[1.  2.  3.  4.  2.3]
[5.  6.  7.  8.  4.5]
[ 6.   8.  10.  12.   6.8]


In [7]:
import numpy as np
l=[[1,2],[3,4],[2.3,4.5]]
k=[[5,6],[7,8],[4.5,4.6]]
ar1 = np.array(l)
ar2 = np.array(k)
print(ar1+ar2)

[[ 6.   8. ]
 [10.  12. ]
 [ 6.8  9.1]]


In [8]:
ar1.size

6

In [9]:
ar1.ndim

2

In [10]:
ar1.dtype

dtype('float64')

In [11]:
ar1.shape

(3, 2)

In [13]:
print(ar1)

[[1.  2. ]
 [3.  4. ]
 [2.3 4.5]]


In [14]:
print(ar2)

[[5.  6. ]
 [7.  8. ]
 [4.5 4.6]]


In [15]:
print(ar1+ar2)

[[ 6.   8. ]
 [10.  12. ]
 [ 6.8  9.1]]


In [16]:
import numpy as np
l=[[1,2],[3,4],[3]]
k=[[5,6],[7,8],[3]]
ar1 = np.array(l)
print(ar1.shape)

(3,)


In [17]:
ar1

array([list([1, 2]), list([3, 4]), list([3])], dtype=object)

In [19]:
print(ar1[0])

[1, 2]


In [20]:
print(ar1[1])

[3, 4]


In [22]:
print(ar1[0:2])

[list([1, 2]) list([3, 4])]


In [24]:
ar1

array([list([1, 2]), list([3, 4]), list([3])], dtype=object)

In [25]:
print(ar1[0:2])

[list([1, 2]) list([3, 4])]


In [29]:
print(ar1[0:2])

[list([1, 2]) list([3, 4])]


In [31]:
print(ar1[0:2,1])

IndexError: too many indices for array

In [32]:
print(type(ar1))

<class 'numpy.ndarray'>


In [33]:
ar1=np.array([1,2,3,4,5,6,7,8])
ar1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
print(ar1)

[1 2 3 4 5 6 7 8]


In [35]:
print(ar1[0:3])

[1 2 3]


In [36]:
print(ar1[0:3,:4])

IndexError: too many indices for array

In [37]:
print(ar1)

[1 2 3 4 5 6 7 8]


In [38]:
ar1[0]

1

In [39]:
ar2[2]

array([4.5, 4.6])

In [40]:
ar1[1]

2

In [41]:
import pandas as pd

In [43]:
l=[1,2,3,4]

In [44]:
s1=pd.Series(data=[1,2,3,4],index=["a","b","c","d"])
print(s1)

a    1
b    2
c    3
d    4
dtype: int64


In [45]:
s1.a

1

In [46]:
s1.b

2